### ISSUE TITLE
Replace `node-sass` with `sass`

### ISSUE THREAD

**Issue by brylie** [creativecommons/vocabulary-components#1]
## Problem
The `node-sass` package is deprecated in favor of `sass`.

## Task

- [ ] replace `node-sass` with `sass`
- [ ] update any related dependencies
- [ ] remove any unneeded dependencies related to `node-sass`
