### ISSUE TITLE
Remove dependency on Vocabulary package

### ISSUE THREAD

**Issue by brylie** [creativecommons/vocabulary-components#10]
We have recently divided the Vocabulary project into separate packages. One of which is `vocabulary-styles`.

Now that the new Vocabulary packages are published, we need to replace the `@creativecommons/vocabulary` dependency in this project with `@creativecommons/vocabulary-styles`, `@creativecommons/vocabulary-fonts` and `@creativecommons/cc-assets`.

## Task

- [x] Remove the `@creativecommons/vocabulary` dependency
- [x] replace the old dependency with any of the new Vocabulary packages that are relevant, such as `@creativeccommons/vocabulary-styles`.
- [x] replace all assets (images, logos, icons) with the `cc-assets` equivalents.

**Comment by MuluhGodson** [comment]
Hello @brylie 
can I be assigned here?
