### ISSUE TITLE
Upgrade or remove direct Bulma dependency

### ISSUE THREAD

**Issue by brylie** [creativecommons/vocabulary-components#14]
We are getting several deprecation warnings related to our Bulma version:

> Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Those warnings have been fixed in the latest Bulma release.

## Task

- [ ] determine whether we need the direct Bulma dependency
- [ ] remove the Bulma dependency if the transient Bulma dependency is sufficient via vocabulary-styles
- [ ] upgrade the Bulma dependency if we need it as a direct dependency

**Comment by sadn1ck** [comment]
The only direct import from bulma seems to be in `AppModal.vue`, and if I comment the import, it seems to function properly.

**Comment by brylie** [comment]
OK, cool. Would you like to open a pull request that removes the direct dependency?

**Comment by sadn1ck** [comment]
Okay another update: just tried uninstalling it, but it seems `bulma` is needed since `vocabulary-styles` doesn't seem to pull it as a dependency, direct, dev, or peer.

**Comment by brylie** [comment]
OK, we should update `vocabulary-styles` to define Bulma as a dependency. Would you please open a bug report in the `vocabulary-styles` project describing the issue?

**Comment by brylie** [comment]
@MuluhGodson, would you double-check this issue?

**Comment by MuluhGodson** [comment]
It will be my pleasure.

**Comment by brylie** [comment]
I would recommend we consider switching to Bootstrap 5 for a few reasons.

- accessibility - accessibility is a first-class concern
- longevity - the project is mature and continues to improve
- high-level - it provides high-level components and concepts (such as grid)
- modern - it follows modern web development practices such as flexbox for layout

I'd rather we avoid using a CSS framework with only one or a couple of primary contributors. Likewise, I'd like to avoid implementing our own component library using a utility-based DSL, such as is done with Tailwind.

**Comment by MuluhGodson** [comment]
Upgrading vocabulary-styles should be able to resolve this issue, I had already submitted a PR in Vocabulary-styles https://github.com/creativecommons/vocabulary-styles/pull/7

As concerns switching to Bootstrap, I support the idea 100%, I think in the context of what we want to achieve, Bootstrap will better serve our needs. Is this switch for the MVP or can we schedule it for post-launch?

**Comment by brylie** [comment]
I've updated the milestone :-)

**Comment by possumbilities** [comment]
Closing this, since this is moving to archived, and no longer on the roadmap
