### ISSUE TITLE
Upgrade dependencies to latest compatible versions, remove unneeded

### ISSUE THREAD

**Issue by brylie** [creativecommons/vocabulary-components#15]
Many of our direct dependencies are out of date. Most likely, some are no longer needed.

## Task

- [ ] audit our dependencies and remove any that are unneeded
- [ ] run `npm outdated`
- [ ] determine which dependencies can be safely updated
- [ ] update the dependencies to the latest compatible versions

**Comment by sadn1ck** [comment]
Are we still planning to keep storybook? It carries a bulk of dependencies all by itself (along with react as a dev dependency for some reason).

**Comment by brylie** [comment]
Yes, I believe we are planning to remove Storybook from this repository. Would you like to take this task and the Storybook removal?

**Comment by sadn1ck** [comment]
What will we be migrating to? I believe we can go ahead with the dependency upgrades in the meanwhile, and decide what to migrate to.

Ideally migration can be done in another PR.

**Comment by sadn1ck** [comment]
Running `npm update` with node 16 resulted in an irreconciliable dependency conflict, and I'm hesitant to use `--force`, not sure what would break.

<details>
<summary> Log </summary>

```vocabulary-components on  chore/deps is 📦 v0.2.0 via  v16.13.1 took 50s 
❯ npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @creativecommons/vocabulary-components@0.2.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   dev react@"^16.13.1" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @storybook/addons@6.4.14
npm ERR!   node_modules/@storybook/addons
npm ERR!     dev @storybook/addons@"^6.0.21" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-dom@17.0.2
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@"^16.8.0 || ^17.0.0" from @storybook/addons@6.4.14
npm ERR!   node_modules/@storybook/addons
npm ERR!     dev @storybook/addons@"^6.0.21" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/anik/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anik/.npm/_logs/2022-01-25T14_09_02_670Z-debug.log```

</details>

**Comment by brylie** [comment]
Further impetus to remove Storybook.
