### ISSUE TITLE
Remove Storybook and related dependencies

### ISSUE THREAD

**Issue by brylie** [creativecommons/vocabulary-components#16]
The Storybook dependency, while exciting, has led to complexity and dependency bloat in the Vocabulary Components. We are working to restore this project to good health, including updating all dependencies. We are considering removing Storybook in order to make dependency management easier. We can consider how to use Storybook via a separate repository, but want to avoid intermixing it into this project.

## Task

- [x] [open a discussion](https://github.com/creativecommons/vocabulary-components/discussions) related to project development and documentation options that are similar to Storybook
- [ ] remove Storybook content, files, and related dependencies
- [ ] remove Storybook-related commands from package.json
- [ ] remove Storybook-related documentation

**Comment by brylie** [comment]
@sadn1ck, would you like this task?

**Comment by sadn1ck** [comment]
Sure @brylie!

**Comment by sadn1ck** [comment]
Related discussion: https://github.com/creativecommons/vocabulary-components/discussions/17

**Comment by brylie** [comment]
I believe we should prioritize this issue, since it is blocking #15
